from __future__ import annotations

from typing import Any, Dict, List, Protocol


class LedgerService(Protocol):
    async def get_eth_balance(self, address: str) -> float: ...
    async def get_token_balance(self, address: str, token_symbol: str) -> float: ...
    async def get_transaction_history(self, address: str, limit: int = 5) -> List[Dict[str, Any]]: ...
    async def get_contract_bytecode(self, address: str) -> str: ...
    async def resolve_ens_domain(self, domain_name: str) -> str: ...
    async def get_token_price(self, token_symbol: str) -> float: ...
    async def check_address_reputation(self, address: str) -> str: ...
    async def simulate_transaction(self, to: str, value: float, data_field: str | None = None) -> Dict[str, Any]: ...
    async def verify_contract_owner(self, contract_address: str) -> str: ...
    async def check_token_approval(self, owner: str, spender: str) -> float: ...
    async def verify_signature(self, message: str, signature: str, address: str) -> bool: ...
    async def transfer_eth(self, to_address: str, amount: float, from_address: str | None = None, idempotency_key: str | None = None) -> Dict[str, Any]: ...
    async def swap_tokens(self, token_in: str, token_out: str, amount: float, address: str | None = None, idempotency_key: str | None = None) -> Dict[str, Any]: ...
    async def approve_token(self, owner: str, spender: str, amount: float, idempotency_key: str | None = None) -> Dict[str, Any]: ...
    async def revoke_approval(self, owner: str, spender: str, idempotency_key: str | None = None) -> Dict[str, Any]: ...
    async def get_liquidity_pool_info(self, token_address: str) -> Dict[str, Any]: ...
    async def bridge_asset(self, token: str, target_chain: str, idempotency_key: str | None = None) -> Dict[str, Any]: ...
    async def stake_tokens(self, protocol: str, amount: float, idempotency_key: str | None = None) -> Dict[str, Any]: ...
